### ISSUE TITLE
labels.txt is missing

### ISSUE THREAD

**Issue by nicolascazard** [ruifcruz/sroie-on-layoutlm#4]
Hi,

I have an issue when I try to run your notebook on the SROIE dataset. The labels.txt file is missing and I have some trouble to understand how to recreate it from the multiple .txt files for each receipt. 
Is there a way to download it somewhere, or could you share the code you use to create it with the right format ?

Thank you

**Comment by nicolascazard** [comment]
This line is the one returning an error, as the file being copied doesn't exists for me, and isn't created anywhere in the notebook :

`cp '/content/drive/My Drive/Msc/Tese/Datasets/SROIE2019/labels.txt' '/content/unilm/layoutlm/examples/seq_labeling/data'
`

**Comment by ninjakx** [comment]
Here: https://github.com/thongn98/receipt-information-extraction/blob/master/data/labels.txt

**Comment by nicolascazard** [comment]
I had misunderstood what this file was supposed to contain, thanks !

**Comment by ruifcruz** [comment]
Hi @nicolascazard , sorry I have missed this block of code. I have just pushed a new version were labels.txt is also written.
