### ISSUE TITLE
Single Image Prediction

### ISSUE THREAD

**Issue by sumeetsuman83** [ruifcruz/sroie-on-layoutlm#6]
Can you please help me out with the prediction of the model generated like how can we predict for a sample image I have?

**Comment by ruifcruz** [comment]
This example is focused on training and evaluate based on the SROIE dataset, which is already available in a txt format. This means that you have to OCR the image (using pytesseract or google vision API, for example) and then convert the OCR'ed text into the SROIE txt format. Then you may apply it to the model which is fine tuned in this notebook

**Comment by sumeetsuman83** [comment]
@ruifcruz I am getting "index out of error in self" while training. I have done all the preprocessing required and generated train.txt along with other files. but it gives an error in the line  
return tourch.embedding(weight,input,padding_idx,scale_grad_by_freq,sparse) while training.
Can you please help.

**Comment by ruifcruz** [comment]
It seems something wrong in your input files. Check if they match the structure given in the sroie examples and if the bounding boxes coordinates are normalized. If you share the files I can try take a look.

**Comment by sumeetsuman83** [comment]
Hi ruifcruz,
Thank you so much for your response and support. I found the issue. My bounding boxes had issues like x2<x1 and also negative x values. It got resolved. Thank you. Also it would be nice if you could edit and add two more lines to filter out such words before saving it to xlsx.
